// Genealogy of Jesus Christ from the Bible
// Matthew 1:1-17 and Luke 3:23-38

window.GenealogyData = {
  // Matthew's genealogy (from Abraham to Jesus, 42 generations)
  // Only David through Jeconiah (kings of Judah) are marked as royal
  matthew: {
    vertices: [
      {_id: 'abraham', name: 'Abraham', generation: 1, source: 'matthew'},
      {_id: 'isaac', name: 'Isaac', generation: 2, source: 'matthew'},
      {_id: 'jacob', name: 'Jacob', generation: 3, source: 'matthew'},
      {_id: 'judah', name: 'Judah', generation: 4, source: 'matthew'},
      {_id: 'perez', name: 'Perez', generation: 5, source: 'matthew'},
      {_id: 'hezron', name: 'Hezron', generation: 6, source: 'matthew'},
      {_id: 'ram', name: 'Ram', generation: 7, source: 'matthew'},
      {_id: 'amminadab', name: 'Amminadab', generation: 8, source: 'matthew'},
      {_id: 'nahshon', name: 'Nahshon', generation: 9, source: 'matthew'},
      {_id: 'salmon', name: 'Salmon', generation: 10, source: 'matthew'},
      {_id: 'boaz', name: 'Boaz', generation: 11, source: 'matthew'},
      {_id: 'obed', name: 'Obed', generation: 12, source: 'matthew'},
      {_id: 'jesse', name: 'Jesse', generation: 13, source: 'matthew'},
      {_id: 'david', name: 'David', generation: 14, royal: true, source: 'matthew'},
      {_id: 'solomon', name: 'Solomon', generation: 15, royal: true, source: 'matthew'},
      {_id: 'rehoboam', name: 'Rehoboam', generation: 16, royal: true, source: 'matthew'},
      {_id: 'abijah', name: 'Abijah', generation: 17, royal: true, source: 'matthew'},
      {_id: 'asa', name: 'Asa', generation: 18, royal: true, source: 'matthew'},
      {_id: 'jehoshaphat', name: 'Jehoshaphat', generation: 19, royal: true, source: 'matthew'},
      {_id: 'jehoram', name: 'Jehoram', generation: 20, royal: true, source: 'matthew'},
      {_id: 'uzziah', name: 'Uzziah', generation: 21, royal: true, source: 'matthew'},
      {_id: 'jotham', name: 'Jotham', generation: 22, royal: true, source: 'matthew'},
      {_id: 'ahaz', name: 'Ahaz', generation: 23, royal: true, source: 'matthew'},
      {_id: 'hezekiah', name: 'Hezekiah', generation: 24, royal: true, source: 'matthew'},
      {_id: 'manasseh', name: 'Manasseh', generation: 25, royal: true, source: 'matthew'},
      {_id: 'amon', name: 'Amon', generation: 26, royal: true, source: 'matthew'},
      {_id: 'josiah', name: 'Josiah', generation: 27, royal: true, source: 'matthew'},
      {_id: 'jeconiah', name: 'Jeconiah', generation: 28, royal: true, source: 'matthew'},
      {_id: 'shealtiel', name: 'Shealtiel', generation: 29, source: 'matthew'},
      {_id: 'zerubbabel', name: 'Zerubbabel', generation: 30, source: 'matthew'},
      {_id: 'abihud', name: 'Abihud', generation: 31, source: 'matthew'},
      {_id: 'eliakim', name: 'Eliakim', generation: 32, source: 'matthew'},
      {_id: 'azor', name: 'Azor', generation: 33, source: 'matthew'},
      {_id: 'zadok', name: 'Zadok', generation: 34, source: 'matthew'},
      {_id: 'achim', name: 'Achim', generation: 35, source: 'matthew'},
      {_id: 'eliud', name: 'Eliud', generation: 36, source: 'matthew'},
      {_id: 'eleazar', name: 'Eleazar', generation: 37, source: 'matthew'},
      {_id: 'matthan', name: 'Matthan', generation: 38, source: 'matthew'},
      {_id: 'jacob_matthew', name: 'Jacob', generation: 39, source: 'matthew', note: 'Father of Joseph'},
      {_id: 'joseph', name: 'Joseph', generation: 40, source: 'matthew', note: 'Husband of Mary'},
      {_id: 'jesus', name: 'Jesus Christ', generation: 41, source: 'matthew'},
      
      // Women in Matthew's genealogy
      {_id: 'tamar', name: 'Tamar', generation: 4, maternal: true, source: 'matthew'},
      {_id: 'rahab', name: 'Rahab', generation: 10, maternal: true, source: 'matthew'},
      {_id: 'ruth', name: 'Ruth', generation: 11, maternal: true, source: 'matthew'},
      {_id: 'bathsheba', name: 'Bathsheba', generation: 15, maternal: true, source: 'matthew'},
      {_id: 'mary', name: 'Mary', generation: 40, maternal: true, source: 'matthew', note: 'Mother of Jesus'}
    ],
    edges: [
      {_out: 'abraham', _in: 'isaac', _label: 'father'},
      {_out: 'isaac', _in: 'jacob', _label: 'father'},
      {_out: 'jacob', _in: 'judah', _label: 'father'},
      {_out: 'judah', _in: 'perez', _label: 'father'},
      {_out: 'tamar', _in: 'perez', _label: 'mother'},
      {_out: 'perez', _in: 'hezron', _label: 'father'},
      {_out: 'hezron', _in: 'ram', _label: 'father'},
      {_out: 'ram', _in: 'amminadab', _label: 'father'},
      {_out: 'amminadab', _in: 'nahshon', _label: 'father'},
      {_out: 'nahshon', _in: 'salmon', _label: 'father'},
      {_out: 'salmon', _in: 'boaz', _label: 'father'},
      {_out: 'rahab', _in: 'boaz', _label: 'mother'},
      {_out: 'boaz', _in: 'obed', _label: 'father'},
      {_out: 'ruth', _in: 'obed', _label: 'mother'},
      {_out: 'obed', _in: 'jesse', _label: 'father'},
      {_out: 'jesse', _in: 'david', _label: 'father'},
      {_out: 'david', _in: 'solomon', _label: 'father'},
      {_out: 'bathsheba', _in: 'solomon', _label: 'mother'},
      {_out: 'solomon', _in: 'rehoboam', _label: 'father'},
      {_out: 'rehoboam', _in: 'abijah', _label: 'father'},
      {_out: 'abijah', _in: 'asa', _label: 'father'},
      {_out: 'asa', _in: 'jehoshaphat', _label: 'father'},
      {_out: 'jehoshaphat', _in: 'jehoram', _label: 'father'},
      {_out: 'jehoram', _in: 'uzziah', _label: 'father'},
      {_out: 'uzziah', _in: 'jotham', _label: 'father'},
      {_out: 'jotham', _in: 'ahaz', _label: 'father'},
      {_out: 'ahaz', _in: 'hezekiah', _label: 'father'},
      {_out: 'hezekiah', _in: 'manasseh', _label: 'father'},
      {_out: 'manasseh', _in: 'amon', _label: 'father'},
      {_out: 'amon', _in: 'josiah', _label: 'father'},
      {_out: 'josiah', _in: 'jeconiah', _label: 'father'},
      {_out: 'jeconiah', _in: 'shealtiel', _label: 'father'},
      {_out: 'shealtiel', _in: 'zerubbabel', _label: 'father'},
      {_out: 'zerubbabel', _in: 'abihud', _label: 'father'},
      {_out: 'abihud', _in: 'eliakim', _label: 'father'},
      {_out: 'eliakim', _in: 'azor', _label: 'father'},
      {_out: 'azor', _in: 'zadok', _label: 'father'},
      {_out: 'zadok', _in: 'achim', _label: 'father'},
      {_out: 'achim', _in: 'eliud', _label: 'father'},
      {_out: 'eliud', _in: 'eleazar', _label: 'father'},
      {_out: 'eleazar', _in: 'matthan', _label: 'father'},
      {_out: 'matthan', _in: 'jacob_matthew', _label: 'father'},
      {_out: 'jacob_matthew', _in: 'joseph', _label: 'father'},
      {_out: 'joseph', _in: 'jesus', _label: 'father'},
      {_out: 'mary', _in: 'jesus', _label: 'mother'}
    ]
  },
  
  // Luke's genealogy (from Jesus to Adam, 77 generations) - simplified version
  luke: {
    vertices: [
      {_id: 'jesus_luke', name: 'Jesus Christ', generation: 1, royal: true, source: 'luke'},
      {_id: 'joseph_luke', name: 'Joseph (Luke)', generation: 2, royal: true, source: 'luke', note: 'Son of Heli'},
      {_id: 'heli', name: 'Heli', generation: 3, royal: true, source: 'luke'},
      {_id: 'matthat', name: 'Matthat', generation: 4, royal: true, source: 'luke'},
      {_id: 'levi_luke', name: 'Levi', generation: 5, royal: true, source: 'luke'},
      {_id: 'melchi', name: 'Melchi', generation: 6, royal: true, source: 'luke'},
      {_id: 'jannai', name: 'Jannai', generation: 7, royal: true, source: 'luke'},
      {_id: 'joseph_luke2', name: 'Joseph', generation: 8, royal: true, source: 'luke'},
      {_id: 'mattathias', name: 'Mattathias', generation: 9, royal: true, source: 'luke'},
      {_id: 'amos', name: 'Amos', generation: 10, royal: true, source: 'luke'},
      {_id: 'nahum', name: 'Nahum', generation: 11, royal: true, source: 'luke'},
      {_id: 'esli', name: 'Esli', generation: 12, royal: true, source: 'luke'},
      {_id: 'naggai', name: 'Naggai', generation: 13, royal: true, source: 'luke'},
      {_id: 'maath', name: 'Maath', generation: 14, royal: true, source: 'luke'},
      {_id: 'mattathias2', name: 'Mattathias', generation: 15, royal: true, source: 'luke'},
      {_id: 'semein', name: 'Semein', generation: 16, royal: true, source: 'luke'},
      {_id: 'josech', name: 'Josech', generation: 17, royal: true, source: 'luke'},
      {_id: 'joda', name: 'Joda', generation: 18, royal: true, source: 'luke'},
      {_id: 'joanan', name: 'Joanan', generation: 19, royal: true, source: 'luke'},
      {_id: 'rhesa', name: 'Rhesa', generation: 20, royal: true, source: 'luke'},
      {_id: 'zerubbabel_luke', name: 'Zerubbabel', generation: 21, royal: true, source: 'luke'},
      {_id: 'shealtiel_luke', name: 'Shealtiel', generation: 22, royal: true, source: 'luke'},
      {_id: 'neri', name: 'Neri', generation: 23, royal: true, source: 'luke'},
      {_id: 'melchi_luke', name: 'Melchi', generation: 24, royal: true, source: 'luke'},
      {_id: 'addi', name: 'Addi', generation: 25, royal: true, source: 'luke'},
      {_id: 'cosam', name: 'Cosam', generation: 26, royal: true, source: 'luke'},
      {_id: 'elmadam', name: 'Elmadam', generation: 27, royal: true, source: 'luke'},
      {_id: 'er', name: 'Er', generation: 28, royal: true, source: 'luke'},
      {_id: 'joshua', name: 'Joshua', generation: 29, royal: true, source: 'luke'},
      {_id: 'eliezer', name: 'Eliezer', generation: 30, royal: true, source: 'luke'},
      {_id: 'jorim', name: 'Jorim', generation: 31, royal: true, source: 'luke'},
      {_id: 'matthat2', name: 'Matthat', generation: 32, royal: true, source: 'luke'},
      {_id: 'levi2', name: 'Levi', generation: 33, royal: true, source: 'luke'},
      {_id: 'simeon', name: 'Simeon', generation: 34, royal: true, source: 'luke'},
      {_id: 'judah_luke', name: 'Judah', generation: 35, royal: true, source: 'luke'},
      {_id: 'joseph_luke3', name: 'Joseph', generation: 36, royal: true, source: 'luke'},
      {_id: 'jonam', name: 'Jonam', generation: 37, royal: true, source: 'luke'},
      {_id: 'eliakim_luke', name: 'Eliakim', generation: 38, royal: true, source: 'luke'},
      {_id: 'melea', name: 'Melea', generation: 39, royal: true, source: 'luke'},
      {_id: 'menna', name: 'Menna', generation: 40, royal: true, source: 'luke'},
      {_id: 'mattatha', name: 'Mattatha', generation: 41, royal: true, source: 'luke'},
      {_id: 'nathan', name: 'Nathan', generation: 42, royal: true, source: 'luke'},
      {_id: 'david_luke', name: 'David', generation: 43, royal: true, source: 'luke'},
      {_id: 'jesse_luke', name: 'Jesse', generation: 44, royal: true, source: 'luke'},
      {_id: 'obed_luke', name: 'Obed', generation: 45, royal: true, source: 'luke'},
      {_id: 'boaz_luke', name: 'Boaz', generation: 46, royal: true, source: 'luke'},
      {_id: 'salmon_luke', name: 'Salmon', generation: 47, royal: true, source: 'luke'},
      {_id: 'nahshon_luke', name: 'Nahshon', generation: 48, royal: true, source: 'luke'},
      {_id: 'amminadab_luke', name: 'Amminadab', generation: 49, royal: true, source: 'luke'},
      {_id: 'ram_luke', name: 'Ram', generation: 50, royal: true, source: 'luke'},
      {_id: 'hezron_luke', name: 'Hezron', generation: 51, royal: true, source: 'luke'},
      {_id: 'perez_luke', name: 'Perez', generation: 52, royal: true, source: 'luke'},
      {_id: 'judah_luke2', name: 'Judah', generation: 53, royal: true, source: 'luke'},
      {_id: 'jacob_luke', name: 'Jacob', generation: 54, royal: true, source: 'luke'},
      {_id: 'isaac_luke', name: 'Isaac', generation: 55, royal: true, source: 'luke'},
      {_id: 'abraham_luke', name: 'Abraham', generation: 56, royal: true, source: 'luke'},
      {_id: 'terah', name: 'Terah', generation: 57, royal: true, source: 'luke'},
      {_id: 'nahor', name: 'Nahor', generation: 58, royal: true, source: 'luke'},
      {_id: 'serug', name: 'Serug', generation: 59, royal: true, source: 'luke'},
      {_id: 'reu', name: 'Reu', generation: 60, royal: true, source: 'luke'},
      {_id: 'peleg', name: 'Peleg', generation: 61, royal: true, source: 'luke'},
      {_id: 'eber', name: 'Eber', generation: 62, royal: true, source: 'luke'},
      {_id: 'shelah', name: 'Shelah', generation: 63, royal: true, source: 'luke'},
      {_id: 'cainan2', name: 'Cainan', generation: 64, royal: true, source: 'luke'},
      {_id: 'arpachshad', name: 'Arpachshad', generation: 65, royal: true, source: 'luke'},
      {_id: 'shem', name: 'Shem', generation: 66, royal: true, source: 'luke'},
      {_id: 'noah', name: 'Noah', generation: 67, royal: true, source: 'luke'},
      {_id: 'lamech', name: 'Lamech', generation: 68, royal: true, source: 'luke'},
      {_id: 'methuselah', name: 'Methuselah', generation: 69, royal: true, source: 'luke'},
      {_id: 'enoch', name: 'Enoch', generation: 70, royal: true, source: 'luke'},
      {_id: 'jared', name: 'Jared', generation: 71, royal: true, source: 'luke'},
      {_id: 'mahalaleel', name: 'Mahalaleel', generation: 72, royal: true, source: 'luke'},
      {_id: 'cainan', name: 'Cainan', generation: 73, royal: true, source: 'luke'},
      {_id: 'enos', name: 'Enos', generation: 74, royal: true, source: 'luke'},
      {_id: 'seth', name: 'Seth', generation: 75, royal: true, source: 'luke'},
      {_id: 'adam', name: 'Adam', generation: 76, royal: true, source: 'luke'}
    ],
    edges: [
      {_out: 'jesus_luke', _in: 'joseph_luke', _label: 'son'},
      {_out: 'joseph_luke', _in: 'heli', _label: 'son'},
      {_out: 'heli', _in: 'matthat', _label: 'father'},
      {_out: 'matthat', _in: 'levi_luke', _label: 'father'},
      {_out: 'levi_luke', _in: 'melchi', _label: 'father'},
      {_out: 'melchi', _in: 'jannai', _label: 'father'},
      {_out: 'jannai', _in: 'joseph_luke2', _label: 'father'},
      {_out: 'joseph_luke2', _in: 'mattathias', _label: 'father'},
      {_out: 'mattathias', _in: 'amos', _label: 'father'},
      {_out: 'amos', _in: 'nahum', _label: 'father'},
      {_out: 'nahum', _in: 'esli', _label: 'father'},
      {_out: 'esli', _in: 'naggai', _label: 'father'},
      {_out: 'naggai', _in: 'maath', _label: 'father'},
      {_out: 'maath', _in: 'mattathias2', _label: 'father'},
      {_out: 'mattathias2', _in: 'semein', _label: 'father'},
      {_out: 'semein', _in: 'josech', _label: 'father'},
      {_out: 'josech', _in: 'joda', _label: 'father'},
      {_out: 'joda', _in: 'joanan', _label: 'father'},
      {_out: 'joanan', _in: 'rhesa', _label: 'father'},
      {_out: 'rhesa', _in: 'zerubbabel_luke', _label: 'father'},
      {_out: 'zerubbabel_luke', _in: 'shealtiel_luke', _label: 'father'},
      {_out: 'shealtiel_luke', _in: 'neri', _label: 'father'},
      {_out: 'neri', _in: 'melchi_luke', _label: 'father'},
      {_out: 'melchi_luke', _in: 'addi', _label: 'father'},
      {_out: 'addi', _in: 'cosam', _label: 'father'},
      {_out: 'cosam', _in: 'elmadam', _label: 'father'},
      {_out: 'elmadam', _in: 'er', _label: 'father'},
      {_out: 'er', _in: 'joshua', _label: 'father'},
      {_out: 'joshua', _in: 'eliezer', _label: 'father'},
      {_out: 'eliezer', _in: 'jorim', _label: 'father'},
      {_out: 'jorim', _in: 'matthat2', _label: 'father'},
      {_out: 'matthat2', _in: 'levi2', _label: 'father'},
      {_out: 'levi2', _in: 'simeon', _label: 'father'},
      {_out: 'simeon', _in: 'judah_luke', _label: 'father'},
      {_out: 'judah_luke', _in: 'joseph_luke3', _label: 'father'},
      {_out: 'joseph_luke3', _in: 'jonam', _label: 'father'},
      {_out: 'jonam', _in: 'eliakim_luke', _label: 'father'},
      {_out: 'eliakim_luke', _in: 'melea', _label: 'father'},
      {_out: 'melea', _in: 'menna', _label: 'father'},
      {_out: 'menna', _in: 'mattatha', _label: 'father'},
      {_out: 'mattatha', _in: 'nathan', _label: 'father'},
      {_out: 'nathan', _in: 'david_luke', _label: 'father'},
      {_out: 'david_luke', _in: 'jesse_luke', _label: 'father'},
      {_out: 'jesse_luke', _in: 'obed_luke', _label: 'father'},
      {_out: 'obed_luke', _in: 'boaz_luke', _label: 'father'},
      {_out: 'boaz_luke', _in: 'salmon_luke', _label: 'father'},
      {_out: 'salmon_luke', _in: 'nahshon_luke', _label: 'father'},
      {_out: 'nahshon_luke', _in: 'amminadab_luke', _label: 'father'},
      {_out: 'amminadab_luke', _in: 'ram_luke', _label: 'father'},
      {_out: 'ram_luke', _in: 'hezron_luke', _label: 'father'},
      {_out: 'hezron_luke', _in: 'perez_luke', _label: 'father'},
      {_out: 'perez_luke', _in: 'judah_luke2', _label: 'father'},
      {_out: 'judah_luke2', _in: 'jacob_luke', _label: 'father'},
      {_out: 'jacob_luke', _in: 'isaac_luke', _label: 'father'},
      {_out: 'isaac_luke', _in: 'abraham_luke', _label: 'father'},
      {_out: 'abraham_luke', _in: 'terah', _label: 'father'},
      {_out: 'terah', _in: 'nahor', _label: 'father'},
      {_out: 'nahor', _in: 'serug', _label: 'father'},
      {_out: 'serug', _in: 'reu', _label: 'father'},
      {_out: 'reu', _in: 'peleg', _label: 'father'},
      {_out: 'peleg', _in: 'eber', _label: 'father'},
      {_out: 'eber', _in: 'shelah', _label: 'father'},
      {_out: 'shelah', _in: 'cainan2', _label: 'father'},
      {_out: 'cainan2', _in: 'arpachshad', _label: 'father'},
      {_out: 'arpachshad', _in: 'shem', _label: 'father'},
      {_out: 'shem', _in: 'noah', _label: 'father'},
      {_out: 'noah', _in: 'lamech', _label: 'father'},
      {_out: 'lamech', _in: 'methuselah', _label: 'father'},
      {_out: 'methuselah', _in: 'enoch', _label: 'father'},
      {_out: 'enoch', _in: 'jared', _label: 'father'},
      {_out: 'jared', _in: 'mahalaleel', _label: 'father'},
      {_out: 'mahalaleel', _in: 'cainan', _label: 'father'},
      {_out: 'cainan', _in: 'enos', _label: 'father'},
      {_out: 'enos', _in: 'seth', _label: 'father'},
      {_out: 'seth', _in: 'adam', _label: 'father'}
    ]
  },
  
  // Default saved queries
  defaultQueries: [
    {
      name: 'Find Jesus',
      query: 'v({name: "Jesus Christ"})'
    },
    {
      name: 'All ancestors of Jesus',
      query: 'v({name: "Jesus Christ"}).in().in().in()'
    },
    {
      name: 'Royal line only',
      query: 'v().filter({royal: true})'
    },
    {
      name: 'Maternal links',
      query: 'v().filter({maternal: true})'
    },
    {
      name: 'Path from Abraham to Jesus',
      query: 'v({name: "Abraham"}).out("father").out("father").out("father")'
    },
    {
      name: 'Kings of Judah (David to Jeconiah)',
      query: 'v().filter({royal: true})'
    }
  ]
};

